#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
	local enabled
	config_load 'ibm'
	config_get enabled ibm_sct 'enable' '0'

	if [ "$enabled" -eq 1 ]; then
		procd_open_instance
		procd_set_param command /usr/bin/ibm
		procd_set_param pidfile /var/run/ibm.pid
		procd_set_param file /etc/config/ibm
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "ibm"
}

reload_service() {
	stop
	start
}
